server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/senac-solid-atividade
    password:
    username:
    driverClassName: org.postgresql.Driver

